export * from './GenresPage/Genres'
export * from './MoviesPage/Movies'
export * from './SearchPage/Search'
export * from './InfoMoviePage/InfoMoviePage'
export * from './GenreMoviesPage/GenreMoviePage'
